"""Add journey_id to support_issues

Revision ID: 12fdae17340b
Revises: 
Create Date: 2025-05-09 03:28:51.316407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12fdae17340b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('journey_id', sa.Integer(), nullable=True))
        batch_op.alter_column('issue_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('issue_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('created_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('resolved_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_support_issues_journey_id', 'journeys', ['journey_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_issues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('resolved_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('created_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('issue_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('issue_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('journey_id')

    # ### end Alembic commands ###
